import { cn } from "@/lib/utils";
import Link from "next/link";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqsArr = [
  {
    question: "Can I edit an estimate generated by the AI?",
    answer:
      "Yes. Open the estimate from your dashboard/projects, click *“Edit,”* make your changes, and save. ",
  },
  {
    question: "How do I send an estimate to a client?",
    answer:
      "Once your estimate is generated, assign it to a project and add a client to that project, click *“Export/Send.”* You can export it as PDF or send it directly by email.",
  },
  {
    question: "Can I add my company logo and details?",
    answer:
      "Yes. Go to *Settings → Company Profile* to upload your logo and business information. These will appear on all estimates",
  },
  {
    question: "What devices can I use QuickEstimate on?",
    answer:
      "QuickEstimate works on desktop, tablet, and mobile browsers. A mobile app version is coming soon.",
  },
  {
    question: "Is my data secure?",
    answer:
      "Yes. QuickEstimate uses industry-standard encryption to keep your data and your clients’ information safe.",
  },
];

function FAQs({ isHome }: { isHome: boolean }) {
  return (
    <div
      className={cn(
        "custom-container  md:bg-transparent",
        isHome ? "bg-white" : "bg-main-blue"
      )}
    >
      <div
        className={cn(
          " md:rounded-4xl w-full flex-col flex gap-10 justify-between items-center p-6  md:p-8 lg:p-12 ",
          isHome ? "bg-transparent" : "bg-main-blue"
        )}
      >
        <div className="w-full max-w-[770px] flex flex-col gap-8">
          <div
            className={cn(
              "flex flex-col items-center gap-1",
              isHome ? "text-black [&_span]:text-[#808080]" : "text-white"
            )}
          >
            <h4 className="text-3xl font-broke-bold font-bold text-center md:text-4xl lg:text-[2.5rem]">
              Your Questions. Answered.
            </h4>
            <span className="text-sm text-center ">
              Answers to all your questions, quickly and clearly
            </span>
          </div>
          <Accordion type="single" collapsible className="w-full ">
            {faqsArr.map((item, index) => (
              <AccordionItem
                value={`item-${index}`}
                key={`accordion-${item.question}`}
                className="mb-4 last:mb-0 border-none"
              >
                <AccordionTrigger
                  className={cn(
                    "rounded-xl justify-start text-black text-sm font-bold font-circular-medium px-6 py-5.5 border-none data-[state=open]:rounded-b-none",
                    isHome ? "bg-[#FAFAFA]" : "bg-white "
                  )}
                >
                  {item.question}
                </AccordionTrigger>
                <AccordionContent
                  className={cn(
                    "px-6 py-4 font-medium rounded-b-xl text-[#5E5E5E]",
                    isHome ? "bg-[#FAFAFA]" : "bg-white "
                  )}
                >
                  {item.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
        <div
          className={cn(
            "rounded-xl flex  p-5.5  items-center border gap-4 justify-between w-full max-w-[770px]",
            isHome ? "text-black border-[#808080]" : "text-white border-white"
          )}
        >
          <div className="flex flex-col">
            <h5 className="text-sm font-bold">
              Still have a question in mind?
            </h5>

            <span
              className={cn(
                "text-sm",
                isHome ? "text-[#808080]" : "text-white"
              )}
            >
              Contact us if you have any other questions.
            </span>
          </div>
          <Link
            href="/contact"
            className={cn(
              "px-5 py-3  hover:shadow-main-blue hover:shadow h-10 items-center justify-center  flex rounded-4xl border border-transparent cursor-pointer text-base font-bold",
              isHome
                ? "bg-main-blue text-white hover:border-main-blue hover:text-main-blue hover:bg-transparent"
                : "bg-white text-main-blue hover:border-white hover:text-white hover:bg-transparent"
            )}
          >
            <span>Contact</span>
          </Link>
        </div>
      </div>
    </div>
  );
}
export default FAQs;
